# Generated by Django 4.2 on 2023-04-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
