# Generated by Django 4.2 on 2023-04-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='teacher/')),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
